baseURL: "http://example.org/"
languageCode: "zh-cn"
defaultContentLanguage: "zh"
title: "Incubator4's Blog"



copyright: ""
theme: minimo
disqusShortname: ""
googleAnalytics: ""
Paginate: 15
preserveTaxonomyNames: true
enableRobotsTXT: true
pygmentsCodefences: true
enableEmoji: true
params:
  info:
    description: 专注Golang,Docker,Kubernetes,云原生 等相关技术
    title404: "走丢啦"
  assets:
    favicon: favicon.ico
    #    customCSS:
    #      - css/custom.css
    #    customJS:
    #      - js/custom.js
    gopher: ""
  copyright:
    prefix: ""
    holder: Incubator4
    startYear: "2018"
    suffix: ""
    beian:
      title: 浙ICP备19012395号-1
      url: http://www.beian.miit.gov.cn/
  settings:
    dateFormat: 2006, Jan 02
    listDateFormat: 2006, Jan 02
    archiveDateFormat: Jan 02
    hideEntryNavigation:
      - page
    hideEntryMeta:
      - page
    showReadingTime: true
    showLastmod: true
    taxonomyCloudShuffle: true
    accentColor: '#66ccff'
    hideMainMenu: false
  sidebar:
    enable: true
  widgets:
    header:
      - breadcrumbs
    homepage:
      - recent_posts
    sidebar:
      - about
      #      - search
      - sidebar_menu
      - taxonomy_cloud
    footer:
      - social_menu
  opengraph:
    facebook:
      admins: [ ]
      appID: ""
      pageID: ""
    twitter:
      page: ""
  seo:
    titleSeparator: •
  social:
    codepen: MunifTanjim
    email: contact@example.com
    facebook: MunifTanjim
    github: MunifTanjim
    gitlab: MunifTanjim
    instagram: MunifTanjim
    linkedin: muniftanjim
    twitter: MunifTanjim
    telegram: MunifTanjim
    google_scholar: qc6CJjYAAAAJ
    youtube: UCT-U0rNerYxItGcuoPX-WYA
  comments:
    enable: false
    isso:
      enable: false
      scriptSrc: ""
      dataAttrs: ""
    staticman:
      enable: true
      apiEndpoint: https://api.staticman.net/v2/entry
      maxDepth: 2
      username: MunifTanjim
      repository: minimo
    utterances:
      enable: false
      issueTerm: pathname
      label: ""
      theme: github-light
      github:
        username: MunifTanjim
        repository: minimo
  search:
    client: fuse
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
permalinks:
  page: /:slug/
menu:
  main:
    - name: Home
      weight: -1
      identifier: home
      url: /
    - name: Tag
      weight: 5
      identifier: tag
      url: /tags
    - name: About
      weight: 90
      identifier: about
      url: /about
    - name: Repo
      weight: 100
      identifier: repository
      url: https://github.com/Incubator4th

blackfriday:
  hrefTargetBlank: true
languages:
  zh:
    lang: zh
    languageName: Chinese
    weight: 1
