name: Deploy

on:
  - push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish Site
        uses: chabad360/hugo-actions@master
        with:
          buildPath: 'public'
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.ALIYUNCS_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUNCS_DOCKER_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          repository: incubator4/hugo-blog
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
      - uses: danielr1996/kubectl-action@1.0.0
        name: Deploy to Kubernetes
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: apply -f deploy.yaml